### ISSUE TITLE
Connecting to a redirector throws "new agent" notification 

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#111]
The new agent is just my normal, ThirdEye agent.

**Comment by lzimm** [comment]
so this is because in order to turn on the tunnel we need to re-initialize the network to listen on `0.0.0.0`, and since we have to re-initialize the network, we have to tear down and restart ThirdEye, and because we treat it as a normal agent connecting over TCP, it triggers the new agent notification, the only way around which is to modify the beacon with a special flag that tells it to stay silent, ala: https://github.com/preludeorg/operator/pull/951

**Comment by lzimm** [comment]
alternatively we can just do this, and enable tunnels without having to tear down the network: https://github.com/preludeorg/operator/pull/952
