### ISSUE TITLE
Limit Node executor to only ThirdEye

### ISSUE THREAD

**Issue by bfuzzy1** [preludeorg/operator-support#144]
Since node executor was removed for agents except ThirdEye. Need a way to check if an agent is ThirdEye then execute if node executor is used. 

Maybe a warning to the user if a procedure contains a node executor to let them know it will only execute on a ThridEye agent as well.

**Comment by privateducky** [comment]
@bfuzzy1 i think this is already being covered with how we handle executors for different agents. Following scenario:

1. Agent has 3 executors: python, keyword, bash
2. Adversary profile contains a TTP which has a node and python executor
3. When deployed, the adversary will use the python executor (since agent doesn't have node). 
4. Another adversary profile contains a TTP with only a node executor
5. This profile is deployed and the TTP will be skipped, which you can find in the agent's results section (click on the skipped link at the top).

**Comment by bfuzzy1** [comment]
@privateducky that actually makes sense. I appreciate the clarification!
