### ISSUE TITLE
Add adversary visualization canvas

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#301]
As a user, I'd like a graph of attack input/output facts, so that I can visualize data flow through an attack chain.

**Comment by privateducky** [comment]
Solidifying the ask here and consolidating with: https://github.com/preludeorg/operator-support/issues/302

- Add a "visualize adversary" button for each profile that pops out a "bubble chart" showing each TTP and how it should/could link to others in the profile.
- In this visualization, allow the user to overlay any other adversary profile to see how it lines up/overlaps. 
- Allow the user to combine adversary profiles from this visualization

**Comment by lzimm** [comment]
so even though a graph would definitely be nice, and is definitely where we're trending towards in a more ideal world, since we don't actually know for sure what facts come out of TTPs until we run them, we don't have a reliable way of actually drawing the edges between nodes in the execution graph before we actually run it, which precludes our ability to do this in a very reliable way.

with that said though, since we do collect a bunch fo historical statistics about all that kind of stuff, we're currently working on some updates to the new adversary sidebar in editor to help support this use case regardless, and to help suggest to users as much as we can (re: the execution flow) without being too overly explicit about things (and not to mislead anyone the way a fully visualized graph might).

i've attached screenshots below, but as you can see, when you launch the adversary sidebar, we display a list of all the TTPs inside the adversary, order it according to how we expect things to be executed by the planner, and when rendering the dependencies of each TTP, allow you to hover over them to highlight other TTPs that might fulfill those dependencies in turn (which though not perfect, attempts to use a couple quick heuristics to provide a reasonable best guess and hopefully help provide at least a little more insight into how things really connect).

![image](https://user-images.githubusercontent.com/139388/135134216-ef09de3c-abcb-4acb-b355-b41da8a5ad98.png)
![image](https://user-images.githubusercontent.com/139388/135134248-51b19dcf-6254-443c-92aa-406b06055f69.png)
![image](https://user-images.githubusercontent.com/139388/135134294-48bce752-22f8-43d6-83c6-39f9c2d64374.png)
