### ISSUE TITLE
Editor: add global edit/save button to technique 

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#323]
I use Editor for viewing/navigating techniques more frequently than editing a technique.  
The default behaviour when clicking on the title, description, and tags is drop into the editor which could result in accidental edits.  I think a safer default is read-only with an explicit edit/save button.

**Comment by privateducky** [comment]
good idea. i'm going to link the "auto save TTPs" ticket on this board, so we can examine both at once: https://github.com/preludeorg/operator-support/issues/260.

soon, we'll be releasing a new version of the Editor, with a quite different look (more like an IDE). this will cover quite a few of the tickets we have open on this board right now, plus a few others we've had on the roadmap. stay tuned for that, between now and version 1.2.

**Comment by lzimm** [comment]
the original implementation of editor had explicit save buttons for everything but this was removed because we had the opposite problem of people losing updates when clicked away. the new editor layout should do a much better job at separating things out though which should greatly reduce the chances of accidental edits on unintentional clicks though. @privateducky can we move this until we collect feedback on the new editor and see how things feel then?

**Comment by privateducky** [comment]
yep, 100%. we'll wait until post 1.2 and revisit.
