### ISSUE TITLE
Add Content Security Policy to Operator

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#335]
- A few months back I started building a CSP for Operator, but I never fully got it across the line.
- Since we have NodeIntegration on (among other things that make the electron app less hardened), we should establish a solid CSP at a minimum.

Check out these links:
- https://www.electronjs.org/docs/tutorial/security
- https://github.com/moloch--/reasonably-secure-electron#preface

**Comment by seijisakurai** [comment]
I tackled it last sprint and gave it a shot again today. Here are my experiences/thoughts:

- I decided to move all inline JavaScript and CSS. Everything works fine if we create new files for desktop.html. 
- Connect.html breaks once we externalize the CSS (I believe anything that touches the sidebar would break too).

Based on my experience my suggestion is to enforce CSP such that it ignores inline CSS and JS for certain html pages. The limitation here is that CSP will not be as effective.

**Comment by privateducky** [comment]
Because the nature of the app is a C2 platform and we're not planning on submitting it to an app-store or similar verification process (of "normal" sec policies), we have no plans to put resources to this effort in the short/mid term. 

That can change if we start moving in a "golden image" direction or determine another use case.
