### ISSUE TITLE
Validate Platform and Executor values on TTP

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#340]
I accidently mistyped the platform on my new TTP as "windos" and the GUI accepted it. I didn't realize it until I tried to deploy and it said "you have no agents available that can run this ttp". I had to look close to figure out it was the typo.

Also, the editor doesn't let you edit the Platform and executor after you have saved your TTP so I had to create a new executor and copy the commands/payloads over and then delete the old executor to get rid of the typo.

Lastly, the examples given for executors doesn't include psh only pwsh. Because of this I assumed that if I wanted either PS core or regular PowerShell I should put pwsh but this wasn't the case. I suggest listed all the viable options or if only psh or pwsh, list psh since that is the most common.

**Comment by privateducky** [comment]
Couple of parts to this ticket:
1. Platforms are in free-text because you may have custom ones, such as rhel, arch, windows2019, or ICS ones like modbus or 1553. We could do some niceties in the future around auto-finding spelling mistakes or offering a list of existing platforms or selecting a new one. But we'll leave this for the future. 
2. It would be nice to allow editing of the platform/executor after the TTP has been saved. We've talked about this one before and I think the reason we didn't initially was due to how we were indexing the TTPs within this section. However, we can look into this again and see if there's an easy solution, as I think you have a point.
3. similar to platforms, executors are free-form and often contain custom values, such as our popular "keyword" executor. we list a few in the example input box but not all. We could change the placeholder text to point the user to the docs for a full list. 

Change requests:
1. Allow editing of platform and/or executor after a TTP has been saved (may require a page reload)
2. Change the placeholder text for executors when building a new TTP.

**Comment by lzimm** [comment]
because this is actually a pretty complex behaviour, i'm invoking a sidebar to contain the behaviour so that we can prevent people from doing this accidentally. should be available in 1.1.2 with the new editor.

![image](https://user-images.githubusercontent.com/139388/132420054-08bbb574-ab80-4ee3-9ca6-d6facefb41c2.png)
