### ISSUE TITLE
"Rebuild adversary" adds unexpected TTPs including Premium ones

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#344]
I'm using the community edition of v1.1

When I create an adversary with the "find recent files" TTP and then set a goal of "file.T1105 contains settings.yml" I am prompted to rebuild adversary. If I say yes, Operator adds 3 more TTPs to my adversary even though I only added one.

1) Parse ssh config
2) Create a crypto key
3) Collect files and compress collection

I don't expect it to add TTPs, I only expect it to remove ones that don't apply. Also, two of these auto-added TTP are premium TTPs that I don't have access to and I can't even manually remove them.

**Comment by privateducky** [comment]
Two parts to this one:
1. When building an adversary from goals, it'll look at all TTPs - community and pro - in order to construct the potential attack paths. We show you professional TTPs if you're on community because it's important you see what a license will get you (no surprises). 
2. when you deploy an adversary with pro ttps while on community, they'll just skip (no executors available). however, we should give you the ability to remove them from pre-built adversaries. 

To-do on this ticket: ensure the "remove" button is not hidden on pro ttps.
