### ISSUE TITLE
Facts are case sensitive but displayed in all upper case

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#345]
Facts are case sensitive but displayed in all upper case so there isn't a way for me to know what case to use when I refer to them. For example, "Find recent files" in T1005 lists expected outputs as "FILE.T1005" (all uppercase) but if I want to set a goal using this fact or otherwise refer to this fact I need to refer to it as "file.T1005" .. or is it "File.T1005" .. or maybe "file.t1005" .. Since the UI doesn't display the proper case, it is hard to know.

![image](https://user-images.githubusercontent.com/22311332/132256901-c85c36aa-1c53-4390-9712-7c5676674643.png)

**Comment by privateducky** [comment]
Agreed. Facts shouldn't be case sensitive.

**Comment by lzimm** [comment]
because this is a bigger lift than we want to do for the next release of operator, we're going to break this up into two parts. the first is to fix the UI so it doesn't force everything to uppercase (which is already committed to dev), then we're going to tweak the core command resolution routines to make them case independent too.

**Comment by privateducky** [comment]
@lzimm what's our status here?

**Comment by lzimm** [comment]
editor should be getting patched to make facts render in their actual case, we haven't modified the actual template injection to make that case insensitive though as it's a bit more delicate than i think we want to visit until a more thorough revisit on that part of the code.
