### ISSUE TITLE
Add "chains" icon to right sidebar

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#353]
Inside Editor, add a new icon to the right sidebar to indicate "chains". 

We should then move the Operate section's chains link/modal to Editor and show the potential chains a person can build from a given TTP.

**Comment by lzimm** [comment]
i'm not sure how useful something like that would actually be in practice because the main thing you allude to there has to do with the input/output dependencies of the ttp in question, both of which are already built into the editor (to the best of what we can do, given the "best attempt" nature of our output fact generation—in the related dependencies and expected outputs part of the right column), which already lets you filter by things that generate the dependencies needed to satisfy the current TTP as well as which TTPs depend on the expected outputs of the current TTP, but I've added an extra sidebar that lets you browse our pre-built chains (as well as render the expected TTP execution order) ala this here https://github.com/preludeorg/plugins/commit/e8e9e309da63f24207d0face1e5d09c80602ce9b:

![image](https://user-images.githubusercontent.com/139388/133161183-f8759078-0980-495d-9948-a8f77b061aba.png)

**Comment by privateducky** [comment]
@lzimm actually, you may be thinking of something else entirely... i'm referring to the 'chains' button inside 'edit ttps' currently, which shows the potential chains you could create (i.e., the TTPs which commonly go together in a real world attack, according to our ATT&CK Procedures program).

**Comment by lzimm** [comment]
ahh, k, fixed here https://github.com/preludeorg/plugins/commit/4eb896967c0434ef3f135bfe58d744f11af3d845, but depends on a fix to gatekeeper because the chain api isn't working:

![image](https://user-images.githubusercontent.com/139388/133187739-f5277ede-4da9-46e3-8be4-d3d601ff5f7f.png)

**Comment by privateducky** [comment]
this is way better treatment for this feature.
