### ISSUE TITLE
Set default range in operate view

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#370]
Colleague requested ability to set a default range to avoid clicking out of the home range each time.

**Comment by tr4cefl0w** [comment]
It would also be nice if Operator could remember the previously selected range.

Current behaviour
* Go to Operator
* Select "Red" range
* Go to Editor
* Go back to Operator, range is back to "Home"
* Select Red range again

Expected behaviour
* Go to Operator
* Select Red range
* Go to Editor
* Go back to Operator, range still is "Red"

**Comment by VVX7** [comment]
a wild colleague appeared!

**Comment by privateducky** [comment]
This has been on my mind, since we re-did the main section in 1.2.

We can pretty easily add state to the page, so it retains the range/agent you have selected now. We'll aim to get that in by 1.3.
