### ISSUE TITLE
Need way to delete ART artifacts without factory reseting operator

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#381]

**Comment by privateducky** [comment]
There are two immediate ways we could do this:
1. add a multi-select delete from the Editor section. 
2. add a delete option in the ART plugin, for specifically ART TTPs.

We've chatted about 1 before, which has some complexities to it. 2 would be pretty doable though, so that's my going recommendation on this one, if someone wants to attempt it (the plugin is open source).

**Comment by khyberspache** [comment]
@privateducky option 2 is fine with me

**Comment by privateducky** [comment]
cool; I've got this on our docket for December.
