### ISSUE TITLE
Cannot delete agent deployment results when connected via redirector

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#397]
I wish I could delete deployment results on my redirector connected agent, like I can with any other agent.

**Comment by privateducky** [comment]
This is an intentional decision, as when you're connected to the redirector it is the owner of your agents. This is a protective measure, allowing you to share your redirectors with your team without anyone having delete privs, which allows you to keep an accurate historical representation of your work. 

Inside Operator, you can only delete agents which connect to your Operator instance. 

If you own the redirector however, you can do one of two things:
1) Log into the headless instance on your redirector as yourself
2) SSH into your redirector and remove the agents from there
