### ISSUE TITLE
"SNIFF NETWORK TRAFFIC" ttp doesn't work

### ISSUE THREAD

**Issue by Eric-Tyrrell22** [preludeorg/operator-support#4]
Command's also overflowing the box.

OS: Catalina 10.15.2

![Screen Shot 2020-11-01 at 11 36 14 AM](https://user-images.githubusercontent.com/58529434/97808770-bc6cf100-1c36-11eb-89d6-a5c46fe553cb.png)

**Comment by privateducky** [comment]
Interesting. @khyberspache thoughts on a good alternative procedure?

**Comment by khyberspache** [comment]
We can probably swap this for something that does a "collect" then parse it after we have the pcap. Lemme think on it

**Comment by khyberspache** [comment]
I think I know what might be causing the issue though - it sleeps for 60 seconds which is probably causing issues with holding open I/O buffers when the server expects an immediate response

**Comment by Eric-Tyrrell22** [comment]
![Screen Shot 2020-11-01 at 6 56 24 PM](https://user-images.githubusercontent.com/58529434/97819048-1a6bf980-1c74-11eb-9505-a8595386130d.png)
Does this command maybe only work on older versions of darwin?

**Comment by khyberspache** [comment]
Okay looking at this from my laptop instead of phone - this command shouldn't work at all, good catch. 

It's missing an actual binary for the first set of arguments... my guess is `nettop` or `tcpdump` like 
```bash
nettop http or port ftp or port smtp or port imap or port pop3 -l -A | egrep -i 'pass=|pwd=|log=|login=|user=|username=|pw=|passw=|passwd=|password=|pass:|user:|username:|password:|login:|pass |user ' --color=auto --line-buffered -B20 & sleep 60; kill $!
```

@privateducky do you know offhand if it's one of these?  `nettop` is OS X native

**Comment by privateducky** [comment]
I have no idea what I was thinking - there should be a big "tcpdump" prepended to that command. 

I updated the TTP, adding this, and optimizing a few other parts. This can be tested if you made an HTTP connection with any of the grepped fields while the command is executing, such as:

```
curl "http://localhost:80/test?password=123"
```

One note is, this TTP is one of the few we currently have which requires sudo privs. It'll fail otherwise, which is OK, but in the future we'll handle this a little different (either avoid running it or attempt to escalate).
