### ISSUE TITLE
QA Baron Samedit (Spawn Agent)

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#412]
tested on AWS linux VM through redirector connection.

1. My main takeaway is to possible rewrite the 'COMPARE SOFTWARE VERSIONS FOR EXPLOITATION' TTP as there is no dpkg already installed or a readily available for AWS linux. With that being said, this ttp will fail and in turn will cause the chain to fail as the fact is creates is needed next for 'Spawn elevated pneuma via CVE-2021-3156'

**Comment by privateducky** [comment]
@khyberspache what are your thoughts on this one?

**Comment by khyberspache** [comment]
I haven't checked if this exploit chain would work on a Fedora-based linux version like this, I only checked on a Debian system.

There are 2 core problems here:
- The compare versions step is an artifact of not being able to do any server-side (operator) side processing of data.
- We use "Linux" to encompass Unix and numerous *nix distros (which is inaccurate)

I don't think it's worth trying to fix TTPs like this because ultimately these TTPs shouldn't exist to begin with. I want to label this "Do not fix" and solve this problem properly.

A proper solution to this would entail:
1. Collecting the version data from the endpoint using the agent
2. Operator itself does the version comparison
3. Version comparison success triggers a new TTP

Back to you @privateducky
