### ISSUE TITLE
Feature Request: Azure redirector provisioning

### ISSUE THREAD

**Issue by sintax1** [preludeorg/operator-support#443]
Similar to AWS and GCP, support for provisioning Azure redirectors would be appreciated.

- Navigate to "Connect" in Prelude Operator
- Select "Provision a New Redirector"
- Prompt for Azure configuration parameters
  - Provider: "Azure"
  - Tenant ID
  - Subscription
  - App ID
  - Secret
- Retrieve available resource groups & prompt user for selection
- Prompt for VM Name
- Deploy

**Comment by privateducky** [comment]
Update: Starting in 1.5, it'll be much more apparent how to stand up redirectors in any environment. We'll still only have support for AWS/GCP automatically but we've simplified the process for people to just deploy manually anywhere. More to come.

**Comment by privateducky** [comment]
Update: 1.5 is now released. It should be more apparent how to deploy redirectors against any cloud now, via "manual redirectors". 

This allows you to pop a redirector up in any cloud environment. 

All automated cloud integration points have moved to the enterprise license starting in 1.5. We will be looking at (automatic) Azure integration at that level but since you can now deploy redirectors on Azure via the main path (manual) I'll close this ticket. Let me know of any concerns!
