### ISSUE TITLE
Feature request: Show version number

### ISSUE THREAD

**Issue by n2vi** [preludeorg/operator-support#448]
It is customary to have an "About" item in one of the menus, often Help, which displays things like version numbers, whether updates are available, subscription type, perhaps even connectivity status to HQ.

If you (or an enterprise security team internally) are trying to assist a novice, this will help with one of the first questions when level-setting over the phone.

Probably should be assigned to whoever gets #426.

**Comment by privateducky** [comment]
Absolutely! In 1.5, we'll be exposing some of that information in the title bar (see below). Thanks for noting the ticket around upgrades - because having some sort of 'updates available' messaging that works well with the ask there makes a lot of sense. 

Starting in 1.5, we'll be supporting multiple versions (for the first time). So instead of a forced upgrade, you'll have a choice of when to do it. Which brings up the need for better messaging. 

More to come on this topic, so I'll keep this issue updated as we have details.

<img width="1434" alt="Screen Shot 2022-03-16 at 7 00 19 AM" src="https://user-images.githubusercontent.com/49954156/158575452-784833b6-a358-430e-b530-a370736c1a36.png">

**Comment by privateducky** [comment]
Closing, as version number is now available in version 1.5. Let me know of any concerns/issues!
