### ISSUE TITLE
Jambi snippet doesn't work when copying from Add agents

### ISSUE THREAD

**Issue by seijisakurai** [preludeorg/operator-support#468]
Two issues need to be resolved:

- When a user clicks on the snippet the formatting is reset. This is not good since `@"` requires it to be in the form of:

`
Add-Type @"`
`using System.Net; using System.Security.Cryptography.X509Certificates; public class TrustAllCertsPolicy : ICertificatePolicy { public bool CheckValidationResult(ServicePoint srvPoint, X509Certificate certificate, WebRequest request, int certificateProblem) { return true; }}`
`"@; `
`[System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy; [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; . ([Scriptblock]::Create((irm -Uri "0.0.0.0:3391/payloads/598a80f66eb96c26452d3358faa1e85686d0bbba/Jambi-Windows.ps1"))) -Address 0.0.0.0:3391`

- Downloading Jambi from Operator doesn't work since Jambi is not stored in the payload folder out of the box.

**Comment by khyberspache** [comment]
Fixes:
- https://github.com/preludeorg/operator/pull/3639
- https://github.com/preludeorg/jambi/pull/1

**Comment by lzimm** [comment]
note: tested both parts of the issue, that the copy and paste maintains formatting, and the payload download

- copy paste works in current master
- downloading payload still fails (though operator now returns a proper error and doesn't hang indefinitely), but that seems to be because the dev outpost has a mismatch between the jambi ttp (which expects `169387d6f3fa5c47c4f4a760fc7fbb0280dd9fde/Jambi-Windows.ps1`) and the actual jambi payload itself (which exists with several other checksums but not that one, though should be migrated—in the TTP file—to `jambi/v1.5/Jambi-Windows.ps1`, which when I hit http://0.0.0.0:3391/payloads/jambi/v1.5/Jambi-Windows.ps1 works fine)

**Comment by khyberspache** [comment]
Yeah for agents we will be using this format:
- http://0.0.0.0:3391/payloads/jambi/v1.5/Jambi-Windows.ps1

moving forwards
