### ISSUE TITLE
Emulate Section: Error when underlying TTP yaml deleted when attached to adversary

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#50]
* we should handle this case gracefully and drop the TTP from the adversary, or mark it as missing

**Comment by privateducky** [comment]
Is there a way this happens aside from manually deleting the file on the OS?

I would only want to cover it if possible (for now). Ideally, we'd cover it either way but until we get to a "polish" priority, I want to focus on causes/effects of things that occur within the app only.

**Comment by khyberspache** [comment]
We don't allow deletes from editor... yet. But that will be adding that soon or if we merge TTPs

**Comment by privateducky** [comment]
kk I think I misread the original context you posted. 

In Editor, since you could delete a TTP, I could see this being an issue for adversaries with it (originally I was thinking this was just if you deleted the file manually on disk).

We should fix this and apply one of your suggestions: remove it from adversaries or mark it as missing. The former seems more natural.

**Comment by lzimm** [comment]
we actually do that when we delete TTPs in the editor: https://github.com/preludeorg/operator/blob/master/static/app/src/editor/components/content.js#L1284

was this actually popping up somewhere?

**Comment by lzimm** [comment]
we now handle cases where we have missing TTPs on Links as well
