### ISSUE TITLE
Root Cause Analysis: Operator/Chains are "broken" and "not working"

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#512]
We get a large number of users reporting "chains are broken" and "nothing is running". Generally, users get to a state like this:
<img width="1612" alt="CleanShot 2022-05-13 at 09 53 25@2x" src="https://user-images.githubusercontent.com/43142871/168299081-003a8703-fc2f-428a-8d57-83f0304e6502.png">

They think the app is broken, but in reality the app is working, the queue is just stalled waiting for some action. These actions might be:
- Missing fact dependencies
- Missing executors

Solution: We need to make it clear why chains/TTPs are not being tasked to an agent in the UI

**Comment by Xanthonus** [comment]
With the changes happening to the chains website we need to better the experience around user defined facts. 

Other than knowing what a user defined fact looks like and looking at the chain and/or knowing that you can go to our current chains website to get the list of user defined facts you really don't know. The other way to get this information is to go and watch our YT videos where in some instances we layout user defined facts. In one chain we have we have like 7 user defined facts so it very easy to miss one if you're not careful.  

A great way to potentially handle this is if a user selects and hits deploy on a chain/ttp that requires a user defined fact that we have a prompt box for each fact not currently in the list and we add it to the fact list. This would completely eliminate this problem entirely.

**Comment by privateducky** [comment]
Predicting fact interpolation is a bit of a hairy area (and separate from this queue one), as facts can be "learned" or provided manually. 

For 1.6, a new feature will shed some more light on it by letting you view your chain by fact dependencies. We don't yet show which facts you have/don't have because we don't have a mechanism in place to determine that (with a high degree of confidence) but it's a starting point:

<img width="1089" alt="Screen Shot 2022-05-13 at 1 37 36 PM" src="https://user-images.githubusercontent.com/49954156/168338234-7c4fa3d7-9036-4c21-9491-0053a52c840e.png">

**Comment by khyberspache** [comment]
Are we adding anything to make it clear what is blocking?

<img width="1612" alt="CleanShot 2022-05-18 at 13 09 17@2x" src="https://user-images.githubusercontent.com/43142871/169114750-e533154d-d6b0-495a-9cf1-23380d13d687.png">

**Comment by privateducky** [comment]
yes. unclear if we'll have it ready for 1.6 though.

**Comment by privateducky** [comment]
We've made changes for 1.6 around messaging, to make this clearer. Beyond that, because this is a pure UX play, I'm closing until 2.0, as we'll have a full refresh on these flows.
