### ISSUE TITLE
v1.6.0 Payload download failed

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#538]
I clicked the paper clip to download dirtypipe.c and get the error:

Download failed. TypeError: Cannot read properties of undefined (reading 'blob')

![image](https://user-images.githubusercontent.com/22311332/170842915-9efbb7fc-b23a-4f0e-bb4a-f7fac78090d9.png)

**Comment by clr2of8** [comment]
Looks like I get the same error when trying to download payloads for any/all TTPs. I'm on Windows 10

**Comment by Xanthonus** [comment]
@privateducky, @khyberspache and I took a look at this.

Im unable to download the payload using the paperclip in the TTP itself and get the same error as @clr2of8 

Error seems to be coming from workspace.js specifically these lines with res being undefined:
`Requests.outpost.getPayload(payload)
                    .then((res) => res.blob())
                    .then((bytes) => Buffer.from(bytes))
                    .then((buffer) => {
                        Basic.createStorage([path.dirname(filename)]);
                        Basic.storeData(Encryption.encryptBuffer(buffer), filename);
                        fs.chmodSync(filename, '755');
                        resolve(buffer);
                    }).catch(err => {
                        reject(err);
                    });`
                    
 There is nothing showing up in the audit.log. 

**Other issues I have experienced along the way:** 
 
Initially, I thought the issue was getting the payload on target. I did an OTA update from 1.5 to 1.6 and was unable to get the payload on target till I did a force reset then everything worked. 
 
Could be my account but I'm also unable to authenticate to portal.prelude.org and unable to view train or docs nor can I use any enterprise features in Connect when logged into my prelude.org email.  The moment I logout I'm able to view train and docs.

**Comment by makk94** [comment]
Brought up a windows VM and can replicate the issue when I download Operator 1.6.0 but can't replicate it when I clone the repo and bring up Operator with the most recent code (using `npm run win:start:prod`)

I assume the bug was fixed by one of the PRs that has gone in in the past month, but if you want more concrete proof, lmk and I can hunt down the PR that did it

**Comment by privateducky** [comment]
ok. marking as solved in 1.7, unless we can get a repro path ahead of release.

**Comment by jaherne** [comment]
@clr2of8 can you try upgrading to 1.7 and let us know if you're still seeing this issue? We've incorporated a fix into the release but want to confirm it's working for you before we close the ticket.

**Comment by clr2of8** [comment]
It says it downloaded to the downloads directory, but it isn't there 
![image](https://user-images.githubusercontent.com/22311332/180898488-3afee399-7259-4e8a-9854-b44add75c095.png)

**Comment by clr2of8** [comment]
Oh, I see it is in the payloads directory. The messaging could be a little better there. I'll submit an issue and make that request.

C:\Users\art\AppData\Roaming\Operator\portal.prelude.org\payloads\ff5d3197ed4f7be37841af1ada7a682d335a892e

You can close this one out as fixed though. Thx
