### ISSUE TITLE
Payloads via redirectors result in UNHANDLED PAYLOAD EXCEPTION

### ISSUE THREAD

**Issue by bartimusprimed** [preludeorg/operator-support#544]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/465079/171548765-b2787295-d86f-4ac7-aceb-ba63ee19bc6b.png">

Was initially reported by discord user occupy_eip, I replicated it with a similar setup.

**Comment by bartimus-primed** [comment]
From what I've seen it's all payloads. When attempting to download it from a redirector.

My setup was:
Local operator instance -> manual redirector on AWS

local pneuma connected to the AWS redirector.

Running a TTP that contains a payload, results in that error.
I didn't include a TTP in the issue because it doesn't seem localized to any specific TTP. The only thing that might be specific is it's a custom payload.
It was pretty late so I didn't try with a outpost hosted payload.
I'll try with an outpost hosted payload right now.

**Comment by bartimus-primed** [comment]
Outpost hosted payloads work fine, from what I see. Seems like this occurs with custom payloads.

**Comment by privateducky** [comment]
ahhh that's really helpful. there must be a dependency missing

**Comment by bartimus-primed** [comment]
So another side effect of this issue is that the redirector will just disconnect instead of erroring out in the TTP.
