### ISSUE TITLE
Directory TTP import fails

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#67]
Repro:
1. Create new TTP
2. Import the directory the TTP is in

**Comment by HarveyVega** [comment]
EDIT: I should note that restarting Operator did not fix it but rebooting the OS did.

Yep, I get the same thing.

I am walking through the training modules and successfully got the flag for Intro>Emulation>Import a New Procedure. I cloned the community git locally and added the 58282d96-4b91-49e8-adaf-eaa3db921b7a.yml file to the execution folder. Then I went to the editor to upload it and instead of uploading the individual file I opted to upload the folder. I got a pop up stating it was done but now when I click on the editor I get the following Unhandled Exception which I've attached a screenshot of
![2021-01-21_18-07](https://user-images.githubusercontent.com/14943426/105429137-6ea0cd00-5c16-11eb-8cfa-93f79089029a.png)

I am running Operator 0.9.13 on Ubuntu 20.04.1 LTS 64bit.

**Comment by metakaos** [comment]
![POerror](https://user-images.githubusercontent.com/6239631/105491950-2e2c6800-5c85-11eb-94a9-b2fbd4c9443f.png)
Reproduced all of the above, including rebooting the OS to successfully import the file, but still get the unhandled exception.
Operator version: 0.9.13
System: Linux 5.10.7-3-MANJARO x86_64 20.2.1 Nibia

**Comment by khyberspache** [comment]
A fix for this is already implemented. It will be available in 0.9.14.
