### ISSUE TITLE
DNS option added to agent 

### ISSUE THREAD

**Issue by bfuzzy1** [preludeorg/operator-support#93]
Would be nice to have DNS capabilities including: DNS over TLS (DoT) and DNS over HTTPS (DoH).

**Comment by privateducky** [comment]
Yes. I think this will be the next supported protocol inside Operator.

**Comment by privateducky** [comment]
@bfuzzy1 i thought long & hard about this one - and thus the concept of translators was born!

We're not going to natively support DNS (or other protocols) inside Operator core code - but it's easy to create translators for Operator protocols, that act as a proxy between agents -> C2.

We wrote two translators: FTP and GRPC. If anyone wants to take a stab at writing a DNS translator, that'd be fantastic - otherwise, we may write one ourselves in the future. Will close this ticket, as the concept is now external to Operator.

**Comment by bfuzzy1** [comment]
I 💯 agree! It's a great concept!
